In [1]:
# Importar bibliotecas
import pandas as pd
# Dados de expectativas de inflação (Focus/BCB)
dados_focus = pd.read_csv(
  filepath_or_buffer = "https://olinda.bcb.gov.br/olinda/servico/Expectativas/versao/v1/odata/ExpectativasMercadoAnuais?%24filter=%28Indicador%20eq%20%27IPCA%27%20or%20Indicador%20eq%20%27IGP-M%27%29%20and%20Data%20ge%20%272023-01-01%27%20and%20Data%20le%20%272023-02-12%27&%24format=text/csv&%24orderby=Data%20desc",
  decimal = ","
  )

In [5]:
dados_focus.groupby(by="DataReferencia").head(1)

,Indicador,IndicadorDetalhe,Data,DataReferencia,Media,Mediana,DesvioPadrao,Minimo,Maximo,numeroRespondentes,baseCalculo
0,IGP-M,NaN,2023-02-10,2023,4.5840,4.5955,0.8950,2.6607,7.8000,73,0
1,IGP-M,NaN,2023-02-10,2024,4.3685,4.0650,1.1936,2.8000,9.9000,56,0
2,IGP-M,NaN,2023-02-10,2025,4.0136,3.9850,0.7051,3.0000,6.0000,50,0
3,IGP-M,NaN,2023-02-10,2026,3.8977,3.6000,0.6957,2.7900,5.5000,47,0
4,IGP-M,NaN,2023-02-10,2027,3.8798,3.8700,0.7446,2.5800,5.5000,42,0
490,IPCA,NaN,2023-01-09,2022,5.6360,5.6169,0.0797,5.3961,5.8692,138,0

In [ ]:
#Define groups and apply line filter
dados_focus.query('baseCalculo == 0').groupby(by=['Indicador','DataReferencia']).apply(lambda x:x.query('Mediana == Mediana.max()'),include_groups=False)

                              IndicadorDetalhe        Data   Media  Mediana  \
Indicador DataReferencia
IGP-M     2023           220               NaN  2023-01-26  4.7997   4.6865
                         240               NaN  2023-01-25  4.8028   4.6865
                         300               NaN  2023-01-20  4.8196   4.6865
          2024           1                 NaN  2023-02-10  4.3685   4.0650
                         101               NaN  2023-02-03  4.3293   4.0650
                         121               NaN  2023-02-02  4.3175   4.0650
                         261               NaN  2023-01-24  4.4373   4.0650
                         281               NaN  2023-01-23  4.4373   4.0650
          2025           142               NaN  2023-02-01  4.0040   3.9900
                         162               NaN  2023-01-31  4.0040   3.9900
                         202               NaN  2023-01-27  4.0064   3.9900
          2026           203               NaN  2023-01-27  3.9528   3.9500
          2027           524               NaN  2023-01-05  4.3276   4.1850
                         544               NaN  2023-01-04  4.1868   4.1850
                         564               NaN  2023-01-03  4.1868   4.1850
IPCA      2022           550               NaN  2023-01-04  5.6463   5.6200
                         570               NaN  2023-01-03  5.6472   5.6200
          2023           10                NaN  2023-02-10  5.7630   5.7883
          2024           11                NaN  2023-02-10  4.0324   4.0000
          2025           12                NaN  2023-02-10  3.7515   3.6000
          2026           13                NaN  2023-02-10  3.7209   3.5000
                         33                NaN  2023-02-09  3.6671   3.5000
                         53                NaN  2023-02-08  3.6616   3.5000
                         73                NaN  2023-02-07  3.6616   3.5000
                         93                NaN  2023-02-06  3.6550   3.5000
                         113               NaN  2023-02-03  3.6487   3.5000
                         133               NaN  2023-02-02  3.5805   3.5000
                         153               NaN  2023-02-01  3.5760   3.5000
                         173               NaN  2023-01-31  3.5590   3.5000
                         193               NaN  2023-01-30  3.5590   3.5000
                         213               NaN  2023-01-27  3.5560   3.5000
                         233               NaN  2023-01-26  3.5287   3.5000
                         253               NaN  2023-01-25  3.5287   3.5000
                         273               NaN  2023-01-24  3.5170   3.5000
                         293               NaN  2023-01-23  3.5172   3.5000
          2027           14                NaN  2023-02-10  3.8021   3.6050

                              DesvioPadrao  Minimo   Maximo  \
Indicador DataReferencia
IGP-M     2023           220        1.3125  2.4830  12.7000
                         240        1.3054  2.4830  12.7000
                         300        1.3049  2.4830  12.7000
          2024           1          1.1936  2.8000   9.9000
                         101        0.9642  3.0000   9.5900
                         121        0.9629  3.0000   9.5900
                         261        1.5832  2.5300  13.7000
                         281        1.5832  2.5300  13.7000
          2025           142        0.7041  2.9200   6.0000
                         162        0.7041  2.9200   6.0000
                         202        0.7096  2.9200   6.0000
          2026           203        0.7678  2.8200   6.3000
          2027           524        0.6461  3.2508   5.5000
                         544        0.5383  3.2508   5.0000
                         564        0.5383  3.2508   5.0000
IPCA      2022           550        0.1071  5.3961   6.1636
                         570        0.1080  5.3961   6.1636
          2023           10         0.4401  3.6387   6.9166
          2024           11         0.5501  3.0000   5.7557
          2025           12         0.6407  2.0000   5.5800
          2026           13         0.6916  2.0000   5.5200
                         33         0.6813  2.0000   5.5200
                         53         0.6860  2.0000   5.5200
                         73         0.6860  2.0000   5.5200
                         93         0.6910  2.0000   5.5200
                         113        0.6906  2.0000   5.5200
                         133        0.6292  2.0000   5.5200
                         153        0.6278  2.0000   5.5200
                         173        0.6062  2.0000   5.5200
                         193        0.6062  2.0000   5.5200
                         213        0.6060  2.0000   5.5200
                         233        0.5962  2.0000   5.5200
                         253        0.5962  2.0000   5.5200
                         273        0.6040  2.0000   5.5200
                         293        0.6070  2.0000   5.5200
          2027           14         0.7066  3.0000   5.5000

                              numeroRespondentes  baseCalculo
Indicador DataReferencia
IGP-M     2023           220                  70            0
                         240                  70            0
                         300                  72            0
          2024           1                    56            0
                         101                  54            0
                         121                  54            0
                         261                  56            0
                         281                  56            0
          2025           142                  49            0
                         162                  49            0
                         202                  48            0
          2026           203                  46            0
          2027           524                   8            0
                         544                   6            0
                         564                   6            0
IPCA      2022           550                 137            0
                         570                 137            0
          2023           10                  142            0
          2024           11                  134            0
          2025           12                  114            0
          2026           13                  106            0
                         33                  106            0
                         53                  104            0
                         73                  104            0
                         93                  102            0
                         113                 103            0
                         133                 104            0
                         153                 105            0
                         173                 104            0
                         193                 104            0
                         213                 105            0
                         233                 104            0
                         253                 104            0
                         273                 102            0
                         293                 101            0
          2027           14                   86            0

In [11]:
dados_focus.query('baseCalculo == 0').groupby(by=['Indicador','DataReferencia'],group_keys=False).apply(lambda x:x.query('Mediana == Mediana.max()'),include_groups=False)

,IndicadorDetalhe,Data,Media,Mediana,DesvioPadrao,Minimo,Maximo,numeroRespondentes,baseCalculo
220,NaN,2023-01-26,4.7997,4.6865,1.3125,2.4830,12.7000,70,0
240,NaN,2023-01-25,4.8028,4.6865,1.3054,2.4830,12.7000,70,0
300,NaN,2023-01-20,4.8196,4.6865,1.3049,2.4830,12.7000,72,0
1,NaN,2023-02-10,4.3685,4.0650,1.1936,2.8000,9.9000,56,0
101,NaN,2023-02-03,4.3293,4.0650,0.9642,3.0000,9.5900,54,0
121,NaN,2023-02-02,4.3175,4.0650,0.9629,3.0000,9.5900,54,0
261,NaN,2023-01-24,4.4373,4.0650,1.5832,2.5300,13.7000,56,0
281,NaN,2023-01-23,4.4373,4.0650,1.5832,2.5300,13.7000,56,0
142,NaN,2023-02-01,4.0040,3.9900,0.7041,2.9200,6.0000,49,0
162,NaN,2023-01-31,4.0040,3.9900,0.7041,2.9200,6.0000,49,0
202,NaN,2023-01-27,4.0064,3.9900,0.7096,2.9200,6.0000,48,0
203,NaN,2023-01-27,3.9528,3.9500,0.7678,2.8200,6.3000,46,0
524,NaN,2023-01-05,4.3276,4.1850,0.6461,3.2508,5.5000,8,0
544,NaN,2023-01-04,4.1868,4.1850,0.5383,3.2508,5.0000,6,0
564,NaN,2023-01-03,4.1868,4.1850,0.5383,3.2508,5.0000,6,0
550,NaN,2023-01-04,5.6463,5.6200,0.1071,5.3961,6.1636,137,0
570,NaN,2023-01-03,5.6472,5.6200,0.1080,5.3961,6.1636,137,0
10,NaN,2023-02-10,5.7630,5.7883,0.4401,3.6387,6.9166,142,0
11,NaN,2023-02-10,4.0324,4.0000,0.5501,3.0000,5.7557,134,0
12,NaN,2023-02-10,3.7515,3.6000,0.6407,2.0000,5.5800,114,0
13,NaN,2023-02-10,3.7209,3.5000,0.6916,2.0000,5.5200,106,0
33,NaN,2023-02-09,3.6671,3.5000,0.6813,2.0000,5.5200,106,0
53,NaN,2023-02-08,3.6616,3.5000,0.6860,2.0000,5.5200,104,0
73,NaN,2023-02-07,3.6616,3.5000,0.6860,2.0000,5.5200,104,0
93,NaN,2023-02-06,3.6550,3.5000,0.6910,2.0000,5.5200,102,0
113,NaN,2023-02-03,3.6487,3.5000,0.6906,2.0000,5.5200,103,0
133,NaN,2023-02-02,3.5805,3.5000,0.6292,2.0000,5.5200,104,0
153,NaN,2023-02-01,3.5760,3.5000,0.6278,2.0000,5.5200,105,0
173,NaN,2023-01-31,3.5590,3.5000,0.6062,2.0000,5.5200,104,0
193,NaN,2023-01-30,3.5590,3.5000,0.6062,2.0000,5.5200,104,0
213,NaN,2023-01-27,3.5560,3.5000,0.6060,2.0000,5.5200,105,0
233,NaN,2023-01-26,3.5287,3.5000,0.5962,2.0000,5.5200,104,0
253,NaN,2023-01-25,3.5287,3.5000,0.5962,2.0000,5.5200,104,0
273,NaN,2023-01-24,3.5170,3.5000,0.6040,2.0000,5.5200,102,0
293,NaN,2023-01-23,3.5172,3.5000,0.6070,2.0000,5.5200,101,0
14,NaN,2023-02-10,3.8021,3.6050,0.7066,3.0000,5.5000,86,0